### ISSUE TITLE
[Platform] Setup Initial Styles Configuration

### ISSUE THREAD

**Issue by gusentanan** [blitzkz23/capstone-sib-curahan-mental-csd-062#1]
### **_User Story_**
**As an** engineer,  
**I want** to be able to create layout in easier way, 
**So that** the development become quickly and efficient.

### **_Acceptance Criteria_**
**Given** Software Engineer does engineering
**When** they want to build a layout 
**Then** use style resource for consistent styling

**Comment by blitzkz23** [comment]
sure
