### ISSUE TITLE
[Journal] Journal Activity

### ISSUE THREAD

**Issue by blitzkz23** [blitzkz23/capstone-sib-curahan-mental-csd-062#10]
### **_User Story_**
**As an** engineer, I want to be able to made an activity
**so that** user could interact with the journal

### **_Acceptance Criteria_**
**Given** an engineer does engineering
**When** they wants to create activity
**Then** journaling activity could be used

**Comment by gusentanan** [comment]
https://github.com/blitzkz23/capstone-sib-curahan-mental-csd-062/blob/e5117ee47009ec6a8d7297c1341d2e50e24f5dcd/app/src/main/java/com/app/curahanmental/ui/journal/JournalFragment.kt#L117-L120

Mas @blitzkz23  saya ketemu bug di bagian delete swipe nya. 
Jadi item pada posisi paling pertama jika terhapus engga sesuai dengan Id item nya, dan item yang terhapus itu item setelahnya (case-nya jika terdapat lebih dari satu item)

**Comment by blitzkz23** [comment]
> https://github.com/blitzkz23/capstone-sib-curahan-mental-csd-062/blob/e5117ee47009ec6a8d7297c1341d2e50e24f5dcd/app/src/main/java/com/app/curahanmental/ui/journal/JournalFragment.kt#L117-L120
> 
> Mas @blitzkz23 saya ketemu bug di bagian delete swipe nya. Jadi item pada posisi paling pertama jika terhapus engga sesuai dengan Id item nya, dan item yang terhapus itu item setelahnya (case-nya jika terdapat lebih dari satu item)

oke thanks mas udaah sy fix kyknya wkwk, coba dicoba lagi

**Comment by gusentanan** [comment]
> > https://github.com/blitzkz23/capstone-sib-curahan-mental-csd-062/blob/e5117ee47009ec6a8d7297c1341d2e50e24f5dcd/app/src/main/java/com/app/curahanmental/ui/journal/JournalFragment.kt#L117-L120
> > 
> > Mas @blitzkz23 saya ketemu bug di bagian delete swipe nya. Jadi item pada posisi paling pertama jika terhapus engga sesuai dengan Id item nya, dan item yang terhapus itu item setelahnya (case-nya jika terdapat lebih dari satu item)
> 
> oke thanks mas udaah sy fix kyknya wkwk, coba dicoba lagi

Mantapp mas kwkwk 👍

**Comment by blitzkz23** [comment]
``> > > https://github.com/blitzkz23/capstone-sib-curahan-mental-csd-062/blob/e5117ee47009ec6a8d7297c1341d2e50e24f5dcd/app/src/main/java/com/app/curahanmental/ui/journal/JournalFragment.kt#L117-L120
> > > 
> > > Mas @blitzkz23 saya ketemu bug di bagian delete swipe nya. Jadi item pada posisi paling pertama jika terhapus engga sesuai dengan Id item nya, dan item yang terhapus itu item setelahnya (case-nya jika terdapat lebih dari satu item)
> > 
> > 
> > oke thanks mas udaah sy fix kyknya wkwk, coba dicoba lagi
> 
> Mantapp mas kwkwk 👍
``

> > > https://github.com/blitzkz23/capstone-sib-curahan-mental-csd-062/blob/e5117ee47009ec6a8d7297c1341d2e50e24f5dcd/app/src/main/java/com/app/curahanmental/ui/journal/JournalFragment.kt#L117-L120
> > > 
> > > Mas @blitzkz23 saya ketemu bug di bagian delete swipe nya. Jadi item pada posisi paling pertama jika terhapus engga sesuai dengan Id item nya, dan item yang terhapus itu item setelahnya (case-nya jika terdapat lebih dari satu item)
> > 
> > 
> > oke thanks mas udaah sy fix kyknya wkwk, coba dicoba lagi
> 
> Mantapp mas kwkwk 👍

`https://github.com/blitzkz23/capstone-sib-curahan-mental-csd-062/commit/391bb4ee42698255161606090b70c5d47ba4cf0c#L117-L120`

**Comment by blitzkz23** [comment]
https://github.com/blitzkz23/capstone-sib-curahan-mental-csd-062/blob/e5117ee47009ec6a8d7297c1341d2e50e24f5dcd/app/src/main/java/com/app/curahanmental/ui/journal/JournalFragment.kt#L79-L94
