### ISSUE TITLE
[Home] Article Activity & Layout

### ISSUE THREAD

**Issue by gusentanan** [blitzkz23/capstone-sib-curahan-mental-csd-062#16]
### **_User Story_**
as a logged-in user i want to be able to see an article that related to mental illness 

### **_Acceptance Criteria_**
**Given** a logged-in user
**When** the user use the app
**Then** provide a list and detail section of the article

**Comment by blitzkz23** [comment]
mas ini dao, dkk, room yang buat artikel emang masih error ya?

**Comment by gusentanan** [comment]
> mas ini dao, dkk, room yang buat artikel emang masih error ya?

iya mas, 
sekarang sudah saya resolve setelah bertarung dengan coroutines flow 😂 , ada beberapa dependencies yang saya upgrade juga

**Comment by blitzkz23** [comment]
> > mas ini dao, dkk, room yang buat artikel emang masih error ya?
> 
> iya mas, sekarang sudah saya resolve setelah bertarung dengan coroutines flow 😂 , ada beberapa dependencies yang saya upgrade juga

mntb mas
