### ISSUE TITLE
[Messages] Support Message Activity and layouting

### ISSUE THREAD

**Issue by blitzkz23** [blitzkz23/capstone-sib-curahan-mental-csd-062#21]
### **_User Story_**
as a logged-in user i want to be able to see and encourage people that have the same mental state as I am.

### **_Acceptance Criteria_**
**Given** a logged-in user
**When** the user use the app
**Then** able to see and post supportive messages

**Comment by blitzkz23** [comment]
Mas @gusentanan, tolong bikinin bagian buat nampilin datannya ;w

**Comment by gusentanan** [comment]
> Mas @gusentanan, tolong bikinin bagian buat nampilin datannya ;w

siapp, mas. RecylcerViewnya berarti ya mas
